config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates:title, presence:true
  validates:body, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book=Book.new
  end

  def create
    @book=Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books=Book.all
      render :index
    end
  end

  def index
    @books=Book.all
    @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class="edit">Editing Book</h1>
<div class="edit_errors">
  <% if @book.errors.any? %>
    <p class="edit_errors_title"> <%= @book.errors.count %> errors prohibted this book from being saved:</p>
    <ul class="edit_errors_ul">
      <% @book.errors.full_messages.each do |message| %>
        <li class="edit_errors_li"><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<%= form_with model: @book do |f| %>
  <p class="edit">Title</p>
  <p class="edit edit_body"><%= f.text_field:title %></p>
  
  <p class="edit">Body</p>
  <p class="edit edit_body"><%= f.text_area:body %></p>
  <div class="edit edit_body"><%= f.submit'Update Book' %></div>
  <div class=edit_button>
    <p class="edit edit_show"><%= link_to"Show", book_path(@book.id) %></p>
    <p class="edit edit_back"><%= link_to"Back", books_path %></p>
  </div>
<% end %>

app/views/books/index.html.erb
<div class="delete_success"><%= flash[:notice] %></div>

<h1 class="index">Books</h1>

<table class="index table">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td class="body"><%= book.body %></td>
      <td class="button"><%= link_to'Show', book_path(book.id) %></td>
      <td class="button"><%= link_to'Edit', edit_book_path(book.id) %></td>
      <td class="button"><%= link_to'Destroy', book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
  <% end %>
</table>


<!--新規投稿画面-->
<h2 class="index new_book">New book</h2>
<div class="index_errors"><% if @book.errors.any? %></div>
  <p class="index_errors_title"><%= @book.errors.count %>　errors prohibited thid book from being saved:</p>
  <ul class="index_errors_ul">
    <% @book.errors.full_messages.each do |message| %>
      <li class="index_errors_li"><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model:@books,url:'/books',method: :post do |f| %>
  <p class="index new">Title</p>
  <p class="index new"><%= f.text_field:title %></p>
  <p class="index new">Body</p>
  <p class="index new"><%= f.text_area:body %></p>
  <div class="index"><%= f.submit 'Create Book' %></div>
<% end %>

app/views/books/show.html.erb
<div class="create_success"><%= flash[:notice] %></div>

<div class="show_title">
  <p class="show_text">Title:</p>
  <p><%= @book.title %></p>
</div>
<div class="show_body">
  <p class="show_text">Body:</p>
  <p><%= @book.body %></p>
</div>

<div class="show_button">
<p class="show_edit"><%= link_to"Edit",edit_book_path(@book.id) %></p>
<p class="show_back"><%= link_to"Back",books_path %></p>
</div>

app/views/homes/top.html.erb
<h1 class="top_head">ようこそ　Bookersへ！</h1>
<div Class="top">Bookers では、さまざまな書籍に関するあなたの意見や</div>
<div Class="top">印象を共有し変換することができます</div>
<div class="top"><%= link_to'start',books_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>